# Generated by Django 3.2.12 on 2023-02-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='idNumber',
        ),
    ]
