# Generated by Django 3.2.12 on 2023-02-11 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_remove_member_idnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acountNumber', models.IntegerField(verbose_name=16)),
                ('balance', models.IntegerField(verbose_name=16)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='accounts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='membercardnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerAcount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberaccounts')),
                ('ownerName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='memberaccounts',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
